export const GET_TRANSPORTES_REQUEST = "GET_TRANSPORTES_REQUEST";
export const GET_TRANSPORTES_SUCCESS = "GET_TRANSPORTES_SUCCESS";
export const GET_TRANSPORTES_FAILED = "GET_TRANSPORTES_FAILED";

export const GET_TIPOS_REQUEST = "GET_TIPOS_REQUEST";
export const GET_TIPOS_SUCCESS = "GET_TIPOS_SUCCESS";
export const GET_TIPOS_FAILED = "GET_TIPOS_FAILED";

export const GET_SUBTIPOS_REQUEST = "GET_SUBTIPOS_REQUEST";
export const GET_SUBTIPOS_SUCCESS = "GET_SUBTIPOS_SUCCESS";
export const GET_SUBTIPOS_FAILED = "GET_SUBTIPOS_FAILED";

export const GET_VENDEDORES_REQUEST = "GET_VENDEDORES_REQUEST";
export const GET_VENDEDORES_SUCCESS = "GET_VENDEDORES_SUCCESS";
export const GET_VENDEDORES_FAILED = "GET_VENDEDORES_FAILED";

export const GET_PORCIVA_REQUEST = "GET_PORCIVA_REQUEST";
export const GET_PORCIVA_SUCCESS = "GET_PORCIVA_SUCCESS";
export const GET_PORCIVA_FAILED = "GET_PORCIVA_FAILED";
