export const GET_TRANSPORTES_REQUEST = "GET_TRANSPORTES_REQUEST";
export const GET_TRANSPORTES_SUCCESS = "GET_TRANSPORTES_SUCCESS";
export const GET_TRANSPORTES_FAILED = "GET_TRANSPORTES_FAILED";

export const GET_VENDEDORES_REQUEST = "GET_VENDEDORES_REQUEST";
export const GET_VENDEDORES_SUCCESS = "GET_VENDEDORES_SUCCESS";
export const GET_VENDEDORES_FAILED = "GET_VENDEDORES_FAILED";

export const GET_PORCIVA_REQUEST = "GET_PORCIVA_REQUEST";
export const GET_PORCIVA_SUCCESS = "GET_PORCIVA_SUCCESS";
export const GET_PORCIVA_FAILED = "GET_PORCIVA_FAILED";

export const GET_PAGOS_REQUEST = "GET_PAGOS_REQUEST";
export const GET_PAGOS_SUCCESS = "GET_PAGOS_SUCCESS";
export const GET_PAGOS_FAILED = "GET_PAGOS_FAILED";

export const GET_NUMEROS_REQUEST = "GET_NUMEROS_REQUEST";
export const GET_NUMEROS_SUCCESS = "GET_NUMEROS_SUCCESS";
export const GET_NUMEROS_FAILED = "GET_NUMEROS_FAILED";

