export const GET_TRANSPORTES_REQUEST = "GET_TRANSPORTES_REQUEST";
export const GET_TRANSPORTES_SUCCESS = "GET_TRANSPORTES_SUCCESS";
export const GET_TRANSPORTES_FAILED = "GET_TRANSPORTES_FAILED";

export const GET_IVA_REQUEST = "GET_IVA_REQUEST";
export const GET_IVA_SUCCESS = "GET_IVA_SUCCESS";
export const GET_IVA_FAILED = "GET_IVA_FAILED";

export const GET_CONCEPTOS_REQUEST = "GET_CONCEPTOS_REQUEST";
export const GET_CONCEPTOS_SUCCESS = "GET_CONCEPTOS_SUCCESS";
export const GET_CONCEPTOS_FAILED = "GET_CONCEPTOS_FAILED";

export const GET_CLIENTES_REQUEST = "GET_CLIENTES_REQUEST";
export const GET_CLIENTES_SUCCESS = "GET_CLIENTES_SUCCESS";
export const GET_CLIENTES_FAILED = "GET_CLIENTES_FAILED";

export const GET_AJUSTES_REQUEST = "GET_AJUSTES_REQUEST";
export const GET_AJUSTES_SUCCESS = "GET_AJUSTES_SUCCESS";
export const GET_AJUSTES_FAILED = "GET_AJUSTES_FAILED";
