name: Excite CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '13'
          cache: 'npm'

      - name: Install dependencies
      - run: npm ci

      - name: build
      - run: npm run build --if-present

      - name: unit test
      - run: npm test
